language: python

python:
  - "3.8"

before_install:
  - sudo apt-get update -qq;
  - sudo apt-get -y install gfortran cmake --fix-missing;
  - sudo apt-get -y install liblapack-dev libblas-dev;
  - sudo apt-get -y install gfortran;
  - pip install scikit-build numpy
  - pip install slycot


install:
  - pip install -r requirements.txt
  - pip install pytest-cov pytest
  - pip install codecov
  - pip install .

script:
  py.test  --cov-report term --cov=kontrol

after_success:
  bash <(curl -s https://codecov.io/bash)
