package:
  name: "kontrol"
  version: "1.0.0-beta"

about:
  summary: "Python package for KAGRA suspension and seismic isolation control."

source:
  path: ..

build:
  script: python setup.py install
